// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface clone$__fn {

    int apply(java.lang.foreign.MemoryAddress _x0);
    static MemorySegment allocate(clone$__fn fi, MemorySession session) {
        return RuntimeHelper.upcallStub(clone$__fn.class, fi, constants$9.clone$__fn$FUNC, session);
    }
    static clone$__fn ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress __x0) -> {
            try {
                return (int)constants$9.clone$__fn$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)__x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


