// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$79 {

    static final FunctionDescriptor io_uring_prep_unlink$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_unlink$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_unlink",
        constants$79.io_uring_prep_unlink$FUNC
    );
    static final FunctionDescriptor io_uring_prep_renameat$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_renameat$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_renameat",
        constants$79.io_uring_prep_renameat$FUNC
    );
    static final FunctionDescriptor io_uring_prep_rename$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_prep_rename$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_rename",
        constants$79.io_uring_prep_rename$FUNC
    );
    static final FunctionDescriptor io_uring_prep_sync_file_range$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_sync_file_range$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_sync_file_range",
        constants$79.io_uring_prep_sync_file_range$FUNC
    );
    static final FunctionDescriptor io_uring_prep_mkdirat$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_mkdirat$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_mkdirat",
        constants$79.io_uring_prep_mkdirat$FUNC
    );
    static final FunctionDescriptor io_uring_prep_mkdir$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_mkdir$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_mkdir",
        constants$79.io_uring_prep_mkdir$FUNC
    );
}


