// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$0 {

    static final FunctionDescriptor io_uring_get_probe_ring$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_get_probe_ring$MH = RuntimeHelper.downcallHandle(
        "io_uring_get_probe_ring",
        constants$0.io_uring_get_probe_ring$FUNC
    );
    static final FunctionDescriptor io_uring_get_probe$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle io_uring_get_probe$MH = RuntimeHelper.downcallHandle(
        "io_uring_get_probe",
        constants$0.io_uring_get_probe$FUNC
    );
    static final FunctionDescriptor io_uring_free_probe$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_free_probe$MH = RuntimeHelper.downcallHandle(
        "io_uring_free_probe",
        constants$0.io_uring_free_probe$FUNC
    );
    static final FunctionDescriptor io_uring_opcode_supported$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_opcode_supported$MH = RuntimeHelper.downcallHandle(
        "io_uring_opcode_supported",
        constants$0.io_uring_opcode_supported$FUNC
    );
    static final FunctionDescriptor io_uring_queue_init_params$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_queue_init_params$MH = RuntimeHelper.downcallHandle(
        "io_uring_queue_init_params",
        constants$0.io_uring_queue_init_params$FUNC
    );
    static final FunctionDescriptor io_uring_queue_init$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_queue_init$MH = RuntimeHelper.downcallHandle(
        "io_uring_queue_init",
        constants$0.io_uring_queue_init$FUNC
    );
}


