// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$11 {

    static final FunctionDescriptor __sched_cpualloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle __sched_cpualloc$MH = RuntimeHelper.downcallHandle(
        "__sched_cpualloc",
        constants$11.__sched_cpualloc$FUNC
    );
    static final FunctionDescriptor __sched_cpufree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __sched_cpufree$MH = RuntimeHelper.downcallHandle(
        "__sched_cpufree",
        constants$11.__sched_cpufree$FUNC
    );
    static final FunctionDescriptor sched_setparam$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sched_setparam$MH = RuntimeHelper.downcallHandle(
        "sched_setparam",
        constants$11.sched_setparam$FUNC
    );
    static final FunctionDescriptor sched_getparam$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sched_getparam$MH = RuntimeHelper.downcallHandle(
        "sched_getparam",
        constants$11.sched_getparam$FUNC
    );
    static final FunctionDescriptor sched_setscheduler$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sched_setscheduler$MH = RuntimeHelper.downcallHandle(
        "sched_setscheduler",
        constants$11.sched_setscheduler$FUNC
    );
    static final FunctionDescriptor sched_getscheduler$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle sched_getscheduler$MH = RuntimeHelper.downcallHandle(
        "sched_getscheduler",
        constants$11.sched_getscheduler$FUNC
    );
}


