// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$21 {

    static final FunctionDescriptor io_uring_prep_symlink$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_prep_symlink$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_symlink",
        constants$21.io_uring_prep_symlink$FUNC
    );
    static final FunctionDescriptor io_uring_prep_linkat$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_linkat$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_linkat",
        constants$21.io_uring_prep_linkat$FUNC
    );
    static final FunctionDescriptor io_uring_prep_link$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_link$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_link",
        constants$21.io_uring_prep_link$FUNC
    );
    static final FunctionDescriptor io_uring_prep_msg_ring$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_msg_ring$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_msg_ring",
        constants$21.io_uring_prep_msg_ring$FUNC
    );
    static final FunctionDescriptor io_uring_prep_getxattr$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle io_uring_prep_getxattr$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_getxattr",
        constants$21.io_uring_prep_getxattr$FUNC
    );
    static final FunctionDescriptor io_uring_prep_setxattr$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle io_uring_prep_setxattr$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_setxattr",
        constants$21.io_uring_prep_setxattr$FUNC
    );
}


