// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$15 {

    static final FunctionDescriptor io_uring_prep_files_update$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_files_update$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_files_update",
        constants$15.io_uring_prep_files_update$FUNC
    );
    static final FunctionDescriptor io_uring_prep_fallocate$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle io_uring_prep_fallocate$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_fallocate",
        constants$15.io_uring_prep_fallocate$FUNC
    );
    static final FunctionDescriptor io_uring_prep_openat$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_openat$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_openat",
        constants$15.io_uring_prep_openat$FUNC
    );
    static final FunctionDescriptor io_uring_prep_openat_direct$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_openat_direct$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_openat_direct",
        constants$15.io_uring_prep_openat_direct$FUNC
    );
    static final FunctionDescriptor io_uring_prep_close$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_close$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_close",
        constants$15.io_uring_prep_close$FUNC
    );
    static final FunctionDescriptor io_uring_prep_close_direct$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_close_direct$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_close_direct",
        constants$15.io_uring_prep_close_direct$FUNC
    );
}


