// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$19 {

    static final FunctionDescriptor io_uring_prep_epoll_ctl$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_prep_epoll_ctl$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_epoll_ctl",
        constants$19.io_uring_prep_epoll_ctl$FUNC
    );
    static final FunctionDescriptor io_uring_prep_provide_buffers$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_provide_buffers$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_provide_buffers",
        constants$19.io_uring_prep_provide_buffers$FUNC
    );
    static final FunctionDescriptor io_uring_prep_remove_buffers$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_remove_buffers$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_remove_buffers",
        constants$19.io_uring_prep_remove_buffers$FUNC
    );
    static final FunctionDescriptor io_uring_prep_shutdown$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_shutdown$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_shutdown",
        constants$19.io_uring_prep_shutdown$FUNC
    );
    static final FunctionDescriptor io_uring_prep_unlinkat$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_unlinkat$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_unlinkat",
        constants$19.io_uring_prep_unlinkat$FUNC
    );
    static final FunctionDescriptor io_uring_prep_unlink$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_unlink$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_unlink",
        constants$19.io_uring_prep_unlink$FUNC
    );
}


