// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$8 {

    static final FunctionDescriptor io_uring_setup$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_setup$MH = RuntimeHelper.downcallHandle(
        "io_uring_setup",
        constants$8.io_uring_setup$FUNC
    );
    static final FunctionDescriptor io_uring_register$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_register$MH = RuntimeHelper.downcallHandle(
        "io_uring_register",
        constants$8.io_uring_register$FUNC
    );
    static final FunctionDescriptor __io_uring_get_cqe$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __io_uring_get_cqe$MH = RuntimeHelper.downcallHandle(
        "__io_uring_get_cqe",
        constants$8.__io_uring_get_cqe$FUNC
    );
    static final FunctionDescriptor io_uring_cq_advance$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_cq_advance$MH = RuntimeHelper.downcallHandle(
        "io_uring_cq_advance",
        constants$8.io_uring_cq_advance$FUNC
    );
    static final FunctionDescriptor io_uring_cqe_seen$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_cqe_seen$MH = RuntimeHelper.downcallHandle(
        "io_uring_cqe_seen",
        constants$8.io_uring_cqe_seen$FUNC
    );
    static final FunctionDescriptor io_uring_sqe_set_data$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_sqe_set_data$MH = RuntimeHelper.downcallHandle(
        "io_uring_sqe_set_data",
        constants$8.io_uring_sqe_set_data$FUNC
    );
}


