// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$39 {

    static final FunctionDescriptor gethostid$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gethostid$MH = RuntimeHelper.downcallHandle(
        "gethostid",
        constants$39.gethostid$FUNC
    );
    static final FunctionDescriptor sync$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle sync$MH = RuntimeHelper.downcallHandle(
        "sync",
        constants$39.sync$FUNC
    );
    static final FunctionDescriptor getpagesize$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle getpagesize$MH = RuntimeHelper.downcallHandle(
        "getpagesize",
        constants$39.getpagesize$FUNC
    );
    static final FunctionDescriptor getdtablesize$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle getdtablesize$MH = RuntimeHelper.downcallHandle(
        "getdtablesize",
        constants$39.getdtablesize$FUNC
    );
    static final FunctionDescriptor truncate$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle truncate$MH = RuntimeHelper.downcallHandle(
        "truncate",
        constants$39.truncate$FUNC
    );
    static final FunctionDescriptor truncate64$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle truncate64$MH = RuntimeHelper.downcallHandle(
        "truncate64",
        constants$39.truncate64$FUNC
    );
}


