// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$9 {

    static final FunctionDescriptor __swab32s$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __swab32s$MH = RuntimeHelper.downcallHandle(
        "__swab32s",
        constants$9.__swab32s$FUNC
    );
    static final FunctionDescriptor __swab64s$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __swab64s$MH = RuntimeHelper.downcallHandle(
        "__swab64s",
        constants$9.__swab64s$FUNC
    );
    static final FunctionDescriptor __swahw32s$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __swahw32s$MH = RuntimeHelper.downcallHandle(
        "__swahw32s",
        constants$9.__swahw32s$FUNC
    );
    static final FunctionDescriptor __swahb32s$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __swahb32s$MH = RuntimeHelper.downcallHandle(
        "__swahb32s",
        constants$9.__swahb32s$FUNC
    );
    static final FunctionDescriptor clone$__fn$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle clone$__fn$MH = RuntimeHelper.downcallHandle(
        constants$9.clone$__fn$FUNC
    );
}


