// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$75 {

    static final FunctionDescriptor io_uring_prep_cancel$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_cancel$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_cancel",
        constants$75.io_uring_prep_cancel$FUNC
    );
    static final FunctionDescriptor io_uring_prep_cancel_fd$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_cancel_fd$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_cancel_fd",
        constants$75.io_uring_prep_cancel_fd$FUNC
    );
    static final FunctionDescriptor io_uring_prep_link_timeout$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_link_timeout$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_link_timeout",
        constants$75.io_uring_prep_link_timeout$FUNC
    );
    static final FunctionDescriptor io_uring_prep_connect$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_connect$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_connect",
        constants$75.io_uring_prep_connect$FUNC
    );
    static final FunctionDescriptor io_uring_prep_files_update$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_files_update$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_files_update",
        constants$75.io_uring_prep_files_update$FUNC
    );
    static final FunctionDescriptor io_uring_prep_fallocate$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle io_uring_prep_fallocate$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_fallocate",
        constants$75.io_uring_prep_fallocate$FUNC
    );
}


