// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$72 {

    static final FunctionDescriptor io_uring_prep_write_fixed$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_write_fixed$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_write_fixed",
        constants$72.io_uring_prep_write_fixed$FUNC
    );
    static final FunctionDescriptor io_uring_prep_recvmsg$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_recvmsg$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_recvmsg",
        constants$72.io_uring_prep_recvmsg$FUNC
    );
    static final FunctionDescriptor io_uring_prep_sendmsg$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_sendmsg$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_sendmsg",
        constants$72.io_uring_prep_sendmsg$FUNC
    );
    static final FunctionDescriptor __io_uring_prep_poll_mask$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle __io_uring_prep_poll_mask$MH = RuntimeHelper.downcallHandle(
        "__io_uring_prep_poll_mask",
        constants$72.__io_uring_prep_poll_mask$FUNC
    );
    static final FunctionDescriptor io_uring_prep_poll_add$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_poll_add$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_poll_add",
        constants$72.io_uring_prep_poll_add$FUNC
    );
    static final FunctionDescriptor io_uring_prep_poll_multishot$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_poll_multishot$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_poll_multishot",
        constants$72.io_uring_prep_poll_multishot$FUNC
    );
}


