// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$6 {

    static final FunctionDescriptor io_uring_unregister_iowq_aff$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_unregister_iowq_aff$MH = RuntimeHelper.downcallHandle(
        "io_uring_unregister_iowq_aff",
        constants$6.io_uring_unregister_iowq_aff$FUNC
    );
    static final FunctionDescriptor io_uring_register_iowq_max_workers$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_register_iowq_max_workers$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_iowq_max_workers",
        constants$6.io_uring_register_iowq_max_workers$FUNC
    );
    static final FunctionDescriptor io_uring_register_ring_fd$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_register_ring_fd$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_ring_fd",
        constants$6.io_uring_register_ring_fd$FUNC
    );
    static final FunctionDescriptor io_uring_unregister_ring_fd$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_unregister_ring_fd$MH = RuntimeHelper.downcallHandle(
        "io_uring_unregister_ring_fd",
        constants$6.io_uring_unregister_ring_fd$FUNC
    );
    static final FunctionDescriptor io_uring_register_buf_ring$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_register_buf_ring$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_buf_ring",
        constants$6.io_uring_register_buf_ring$FUNC
    );
    static final FunctionDescriptor io_uring_unregister_buf_ring$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_unregister_buf_ring$MH = RuntimeHelper.downcallHandle(
        "io_uring_unregister_buf_ring",
        constants$6.io_uring_unregister_buf_ring$FUNC
    );
}


