// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$18 {

    static final FunctionDescriptor io_uring_recvmsg_cmsg_firsthdr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_recvmsg_cmsg_firsthdr$MH = RuntimeHelper.downcallHandle(
        "io_uring_recvmsg_cmsg_firsthdr",
        constants$18.io_uring_recvmsg_cmsg_firsthdr$FUNC
    );
    static final FunctionDescriptor io_uring_recvmsg_cmsg_nexthdr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_recvmsg_cmsg_nexthdr$MH = RuntimeHelper.downcallHandle(
        "io_uring_recvmsg_cmsg_nexthdr",
        constants$18.io_uring_recvmsg_cmsg_nexthdr$FUNC
    );
    static final FunctionDescriptor io_uring_recvmsg_payload$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_recvmsg_payload$MH = RuntimeHelper.downcallHandle(
        "io_uring_recvmsg_payload",
        constants$18.io_uring_recvmsg_payload$FUNC
    );
    static final FunctionDescriptor io_uring_recvmsg_payload_length$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_recvmsg_payload_length$MH = RuntimeHelper.downcallHandle(
        "io_uring_recvmsg_payload_length",
        constants$18.io_uring_recvmsg_payload_length$FUNC
    );
    static final FunctionDescriptor io_uring_prep_openat2$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_prep_openat2$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_openat2",
        constants$18.io_uring_prep_openat2$FUNC
    );
    static final FunctionDescriptor io_uring_prep_openat2_direct$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_openat2_direct$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_openat2_direct",
        constants$18.io_uring_prep_openat2_direct$FUNC
    );
}


