// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$9 {

    static final FunctionDescriptor io_uring_cqe_get_data$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_cqe_get_data$MH = RuntimeHelper.downcallHandle(
        "io_uring_cqe_get_data",
        constants$9.io_uring_cqe_get_data$FUNC
    );
    static final FunctionDescriptor io_uring_sqe_set_data64$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle io_uring_sqe_set_data64$MH = RuntimeHelper.downcallHandle(
        "io_uring_sqe_set_data64",
        constants$9.io_uring_sqe_set_data64$FUNC
    );
    static final FunctionDescriptor io_uring_cqe_get_data64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_cqe_get_data64$MH = RuntimeHelper.downcallHandle(
        "io_uring_cqe_get_data64",
        constants$9.io_uring_cqe_get_data64$FUNC
    );
    static final FunctionDescriptor io_uring_sqe_set_flags$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_sqe_set_flags$MH = RuntimeHelper.downcallHandle(
        "io_uring_sqe_set_flags",
        constants$9.io_uring_sqe_set_flags$FUNC
    );
    static final FunctionDescriptor __io_uring_set_target_fixed_file$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle __io_uring_set_target_fixed_file$MH = RuntimeHelper.downcallHandle(
        "__io_uring_set_target_fixed_file",
        constants$9.__io_uring_set_target_fixed_file$FUNC
    );
    static final FunctionDescriptor io_uring_prep_rw$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle io_uring_prep_rw$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_rw",
        constants$9.io_uring_prep_rw$FUNC
    );
}


