// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$35 {

    static final FunctionDescriptor getlogin_r$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle getlogin_r$MH = RuntimeHelper.downcallHandle(
        "getlogin_r",
        constants$35.getlogin_r$FUNC
    );
    static final FunctionDescriptor setlogin$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle setlogin$MH = RuntimeHelper.downcallHandle(
        "setlogin",
        constants$35.setlogin$FUNC
    );
    static final  OfAddress optarg$LAYOUT = Constants$root.C_POINTER$LAYOUT;
    static final VarHandle optarg$VH = constants$35.optarg$LAYOUT.varHandle();
    static final MemorySegment optarg$SEGMENT = RuntimeHelper.lookupGlobalVariable("optarg", constants$35.optarg$LAYOUT);
    static final  OfInt optind$LAYOUT = Constants$root.C_INT$LAYOUT;
    static final VarHandle optind$VH = constants$35.optind$LAYOUT.varHandle();
    static final MemorySegment optind$SEGMENT = RuntimeHelper.lookupGlobalVariable("optind", constants$35.optind$LAYOUT);
    static final  OfInt opterr$LAYOUT = Constants$root.C_INT$LAYOUT;
    static final VarHandle opterr$VH = constants$35.opterr$LAYOUT.varHandle();
    static final MemorySegment opterr$SEGMENT = RuntimeHelper.lookupGlobalVariable("opterr", constants$35.opterr$LAYOUT);
    static final  OfInt optopt$LAYOUT = Constants$root.C_INT$LAYOUT;
    static final VarHandle optopt$VH = constants$35.optopt$LAYOUT.varHandle();
    static final MemorySegment optopt$SEGMENT = RuntimeHelper.lookupGlobalVariable("optopt", constants$35.optopt$LAYOUT);
}


