// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$66 {

    static final FunctionDescriptor io_uring_register_files_update_tag$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_register_files_update_tag$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_files_update_tag",
        constants$66.io_uring_register_files_update_tag$FUNC
    );
    static final FunctionDescriptor io_uring_unregister_files$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_unregister_files$MH = RuntimeHelper.downcallHandle(
        "io_uring_unregister_files",
        constants$66.io_uring_unregister_files$FUNC
    );
    static final FunctionDescriptor io_uring_register_files_update$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_register_files_update$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_files_update",
        constants$66.io_uring_register_files_update$FUNC
    );
    static final FunctionDescriptor io_uring_register_eventfd$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_register_eventfd$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_eventfd",
        constants$66.io_uring_register_eventfd$FUNC
    );
    static final FunctionDescriptor io_uring_register_eventfd_async$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_register_eventfd_async$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_eventfd_async",
        constants$66.io_uring_register_eventfd_async$FUNC
    );
    static final FunctionDescriptor io_uring_unregister_eventfd$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_unregister_eventfd$MH = RuntimeHelper.downcallHandle(
        "io_uring_unregister_eventfd",
        constants$66.io_uring_unregister_eventfd$FUNC
    );
}


