// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$37 {

    static final FunctionDescriptor vhangup$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle vhangup$MH = RuntimeHelper.downcallHandle(
        "vhangup",
        constants$37.vhangup$FUNC
    );
    static final FunctionDescriptor revoke$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle revoke$MH = RuntimeHelper.downcallHandle(
        "revoke",
        constants$37.revoke$FUNC
    );
    static final FunctionDescriptor profil$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle profil$MH = RuntimeHelper.downcallHandle(
        "profil",
        constants$37.profil$FUNC
    );
    static final FunctionDescriptor acct$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle acct$MH = RuntimeHelper.downcallHandle(
        "acct",
        constants$37.acct$FUNC
    );
    static final FunctionDescriptor getusershell$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle getusershell$MH = RuntimeHelper.downcallHandle(
        "getusershell",
        constants$37.getusershell$FUNC
    );
    static final FunctionDescriptor endusershell$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle endusershell$MH = RuntimeHelper.downcallHandle(
        "endusershell",
        constants$37.endusershell$FUNC
    );
}


