// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$13 {

    static final FunctionDescriptor __sighandler_t$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle __sighandler_t$MH = RuntimeHelper.downcallHandle(
        constants$13.__sighandler_t$FUNC
    );
    static final FunctionDescriptor __sysv_signal$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __sysv_signal$MH = RuntimeHelper.downcallHandle(
        "__sysv_signal",
        constants$13.__sysv_signal$FUNC
    );
    static final FunctionDescriptor sysv_signal$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sysv_signal$MH = RuntimeHelper.downcallHandle(
        "sysv_signal",
        constants$13.sysv_signal$FUNC
    );
    static final FunctionDescriptor signal$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle signal$MH = RuntimeHelper.downcallHandle(
        "signal",
        constants$13.signal$FUNC
    );
    static final FunctionDescriptor kill$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle kill$MH = RuntimeHelper.downcallHandle(
        "kill",
        constants$13.kill$FUNC
    );
}


