// Generated by jextract

package io.uring;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$17 {

    static final FunctionDescriptor sigismember$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle sigismember$MH = RuntimeHelper.downcallHandle(
        "sigismember",
        constants$17.sigismember$FUNC
    );
    static final FunctionDescriptor sigisemptyset$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sigisemptyset$MH = RuntimeHelper.downcallHandle(
        "sigisemptyset",
        constants$17.sigisemptyset$FUNC
    );
    static final FunctionDescriptor sigandset$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sigandset$MH = RuntimeHelper.downcallHandle(
        "sigandset",
        constants$17.sigandset$FUNC
    );
    static final FunctionDescriptor sigorset$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sigorset$MH = RuntimeHelper.downcallHandle(
        "sigorset",
        constants$17.sigorset$FUNC
    );
    static final FunctionDescriptor sigprocmask$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sigprocmask$MH = RuntimeHelper.downcallHandle(
        "sigprocmask",
        constants$17.sigprocmask$FUNC
    );
    static final FunctionDescriptor sigsuspend$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sigsuspend$MH = RuntimeHelper.downcallHandle(
        "sigsuspend",
        constants$17.sigsuspend$FUNC
    );
}


